version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
  
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  
  nginx:
    # 这个服务有build字段但值为空，可能不会被正确移除
    build: 
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: myapp

volumes:
  postgres_data: