name: 可复用构建

on:
  workflow_call:
    inputs:
      # 需要检出的 Git 仓库地址
      source_repo:
        required: true
        type: string
      # 推送到 Docker Hub 的镜像名称
      docker_image_name:
        required: true
        type: string
      # Dockerfile 路径，默认为项目根目录
      dockerfile_path:
        required: false
        type: string
        default: "Dockerfile"
      # 构建上下文路径，默认为项目根目录
      context_path:
        required: false
        type: string
        default: "."
      # 额外的 Docker 构建参数（JSON 格式）
      build_args:
        required: false
        type: string
        default: "{}"
      # 是否构建多个 Dockerfile（JSON 数组格式）
      multi_dockerfiles:
        required: false
        type: string
        default: "[]"
    secrets:
      # 调用时需要传入的 secrets
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # 如果提供了 multi_dockerfiles 参数，则使用它来构建多个 Dockerfile
        # 否则使用单个 dockerfile_path 构建一个 Dockerfile
        dockerfile_config: ${{ fromJSON(inputs.multi_dockerfiles) || fromJSON(format('[{"path": "%s", "context": "%s", "args": %s}]', inputs.dockerfile_path, inputs.context_path, inputs.build_args)) }}
    steps:
      - name: 检出目标仓库
        uses: actions/checkout@main
        with:
          repository: ${{ inputs.source_repo }}

      - name: 设置 QEMU
        uses: docker/setup-qemu-action@master

      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: 登录 Docker Hub
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 获取当前日期
        id: date
        run: echo "tag=$(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT

      - name: 提取 Docker 元数据
        id: meta
        uses: docker/metadata-action@master
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.docker_image_name }}
          tags: |
            # 类型 'raw' 用于创建一个固定的 'latest' 标签
            type=raw,value=latest
            # 类型 'schedule' 用于基于计划任务的事件
            # pattern={{date 'YYYY.MM.DD'}} 会自动获取当前日期并格式化
            #type=schedule,pattern={{date 'YYYY.MM.DD'}}
            type=raw,value=${{ steps.date.outputs.tag }}

      - name: Print Docker Tags
        run: |
          echo "Generated tags are:"
          echo "${{ steps.meta.outputs.tags }}"

      - name: 构建并且推送 Docker 镜像
        uses: docker/build-push-action@master
        with:
          context: ${{ matrix.dockerfile_config.context || '.' }}
          file: ${{ matrix.dockerfile_config.path || 'Dockerfile' }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: ${{ toJSON(matrix.dockerfile_config.args) }}
