name: 可复用构建

on:
  workflow_call:
    inputs:
      # 需要检出的 Git 仓库地址
      source_repo:
        required: true
        type: string
      # 推送到 Docker Hub 的镜像名称
      docker_image_name:
        required: true
        type: string
    secrets:
      # 调用时需要传入的 secrets
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出目标仓库
        uses: actions/checkout@main
        with:
          repository: ${{ inputs.source_repo }}

      - name: 设置 QEMU
        uses: docker/setup-qemu-action@master

      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: 登录 Docker Hub
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: 获取当前日期
        id: date
        run: echo "DATE_TAG=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
        
      - name: Verify Date Tag
        run: echo "The date tag from env is: ${{ env.DATE_TAG }}"
        
      - name: 提取 Docker 元数据
        id: meta
        uses: docker/metadata-action@master
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.docker_image_name }}
          tags: |
            # 类型 'raw' 用于创建一个固定的 'latest' 标签
            type=raw,value=latest
            # 类型 'schedule' 用于基于计划任务的事件
            # pattern={{date 'YYYY.MM.DD'}} 会自动获取当前日期并格式化
            #type=schedule,pattern={{date 'YYYY.MM.DD'}}
            type=raw,value=${{env.DATE_TAG}}
      - name: Print Docker Tags
        run: |
          echo "Generated tags are:"
          echo "${{ steps.meta.outputs.tags }}"
          
      - name: 构建并且推送 Docker 镜像
        uses: docker/build-push-action@master
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
