name: 简单Docker构建

on:
  workflow_call:
    inputs:
      # 需要检出的 Git 仓库地址
      source_repo:
        required: true
        type: string
      # 推送到 Docker Hub 的镜像名称
      docker_image_name:
        required: true
        type: string
      # Dockerfile 路径，默认为项目根目录
      dockerfile_path:
        required: false
        type: string
        default: "Dockerfile"
      # 构建上下文路径，默认为项目根目录
      context_path:
        required: false
        type: string
        default: "."
    secrets:
      # 调用时需要传入的 secrets
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出目标仓库
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.source_repo }}

      - name: 设置 QEMU
        uses: docker/setup-qemu-action@v2

      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: 登录 Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 获取当前日期
        id: date
        run: echo "tag=$(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT

      - name: 提取 Docker 元数据
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.docker_image_name }}
          tags: |
            type=raw,value=latest
            type=raw,value=${{ steps.date.outputs.tag }}

      - name: Print Docker Tags
        run: |
          echo "Generated tags are:"
          echo "${{ steps.meta.outputs.tags }}"

      - name: 构建并且推送 Docker 镜像
        uses: docker/build-push-action@v4
        with:
          context: ${{ inputs.context_path }}
          file: ${{ inputs.dockerfile_path }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}