name: 主任务

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  # 定义一个 job 来调用可复用工作流
  call-reusable-workflow:
    # 使用矩阵来为多个仓库分别调用
    strategy:
      fail-fast: false
      matrix:
        include:
          - repo: 'li88iioo/Photonix'
            image_name: 'photonix'
          # - repo: 'another-user/another-repo'
          #   image_name: 'another-app'
    uses: ./.github/workflows/docker-build-reusable.yml
    with:
      source_repo: ${{ matrix.repo }}
      docker_image_name: ${{ matrix.image_name }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
