name: 主任务

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  # 构建li88iioo/Photonix项目（单个Dockerfile在根目录）
  build-photonix:
    uses: ./.github/workflows/docker-build-simple.yml
    with:
      source_repo: 'li88iioo/Photonix'
      docker_image_name: 'photonix'
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  # 构建JefferyHcool/BiliNote后端（Dockerfile在backend目录）
  build-bili-note-backend:
    uses: ./.github/workflows/docker-build-simple.yml
    with:
      source_repo: 'JefferyHcool/BiliNote'
      docker_image_name: 'bili-note-backend'
      dockerfile_path: 'backend/Dockerfile'
      context_path: 'backend'
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  # 构建JefferyHcool/BiliNote前端（Dockerfile在BillNote_frontend目录）
  build-bili-note-frontend:
    uses: ./.github/workflows/docker-build-simple.yml
    with:
      source_repo: 'JefferyHcool/BiliNote'
      docker_image_name: 'bili-note-frontend'
      dockerfile_path: 'BillNote_frontend/Dockerfile'
      context_path: 'BillNote_frontend'
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
