name: 主任务

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:

  # 使用Dockerfile构建li88iioo/Photonix
  build-photonix:
    uses: ./.github/workflows/docker-build.yml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      source_repo: 'li88iioo/Photonix'
      docker_image_name: 'photonix'

  # 使用docker-compose构建BiliNote
  build-bilinote:
    uses: ./.github/workflows/docker-build.yml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      source_repo: 'JefferyHcool/BiliNote'
      docker_image_name: 'bili-note'
      use_compose_build: true
      compose_file_path: 'docker-compose.yml'
      additional_files_to_copy: '[{"source": ".env.example", "destination": ".env"}]'

  # 清除旧的workflow运行记录
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: 删除旧 Actions
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.CLEANUP_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 2