name: 迁移第三方镜像到DockerHub
on:
  workflow_dispatch: # 手动触发，页面填参数

inputs:
  source_repo:
    description: 固定写当前迁移仓库（因为Dockerfile在本仓库）
    default: ${{ github.repository }}
    type: string
  src_docker_image:
    description: 待迁移源镜像（ghcr.io/xxx/xxx:latest、quay.io/xxx 等）
    required: true
    type: string
  docker_image_name:
    description: DockerHub仓库名（你的hub用户名/后面部分，如 mcsm-daemon）
    required: true
    type: string

jobs:
  migrate-image:
    uses: ./.github/workflows/build.yml
    with:
      source_repo: ${{ github.inputs.source_repo }}
      docker_image_name: ${{ github.inputs.docker_image_name }}
      dockerfile_path: ""
      use_custom_dockerfile: true
      custom_dockerfile_path: dockerfiles/migrate-template.Dockerfile
      context_path: "."
      additional_files_to_copy: |
        [{"source":"","destination":"","build_arg":"SRC_IMG=${{ github.inputs.src_docker_image }}"}]
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
